[2025-01-22T17:17:28.787+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T17:17:28.823+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2025-01-22T17:17:07.209384+00:00 [queued]>
[2025-01-22T17:17:28.846+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2025-01-22T17:17:07.209384+00:00 [queued]>
[2025-01-22T17:17:28.848+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-22T17:17:29.046+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): inaccurate> on 2025-01-22 17:17:07.209384+00:00
[2025-01-22T17:17:29.057+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=493) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-22T17:17:29.060+0000] {standard_task_runner.py:72} INFO - Started process 498 to run task
[2025-01-22T17:17:29.060+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2025-01-22T17:17:07.209384+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmp3z5359m0']
[2025-01-22T17:17:29.062+0000] {standard_task_runner.py:105} INFO - Job 64: Subtask inaccurate
[2025-01-22T17:17:29.144+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag.inaccurate manual__2025-01-22T17:17:07.209384+00:00 [running]> on host f20f83373f6a
[2025-01-22T17:17:29.287+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T17:17:07.209384+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T17:17:07.209384+00:00'
[2025-01-22T17:17:29.290+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T17:17:29.291+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T17:17:29.293+0000] {logging_mixin.py:190} INFO - Current task name:inaccurate state:running start_date:2025-01-22 17:17:28.825175+00:00
[2025-01-22T17:17:29.293+0000] {logging_mixin.py:190} INFO - Dag name:my_dag and current dag run status:running
[2025-01-22T17:17:29.295+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T17:17:29.297+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T17:17:29.299+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2025-01-22T17:17:29.315+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T17:17:29.317+0000] {subprocess.py:106} INFO - inaccurate
[2025-01-22T17:17:29.318+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-22T17:17:29.363+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T17:17:29.365+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=manual__2025-01-22T17:17:07.209384+00:00, execution_date=20250122T171707, start_date=20250122T171728, end_date=20250122T171729
[2025-01-22T17:17:29.387+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-22T17:17:29.388+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-22T17:17:29.389+0000] {logging_mixin.py:190} INFO - Dag name:my_dag queued_at:2025-01-22 17:17:07.277508+00:00
[2025-01-22T17:17:29.390+0000] {logging_mixin.py:190} INFO - Task hostname:f20f83373f6a operator:BashOperator
[2025-01-22T17:17:29.440+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T17:17:29.471+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-22T17:17:29.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
